source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'

pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

pod 'pop', '~> 1.0'

pod 'ACEExpandableTextCell'

pod 'IQKeyboardManager'

pod 'CustomIOSAlertView', '~> 0.9.3'

pod 'AFNetworking'

pod 'MJRefresh'

pod 'Reachability'

pod 'SDWebImage'

pod 'PopMenu'

pod 'Qiniu'

pod 'Pingpp/Alipay', '~> 2.1.0'

pod 'Pingpp/Wx', '~> 2.1.0'

pod 'UITableView+FDTemplateLayoutCell', '~> 1.4.beta'

pod 'ZWIntroductionViewController'
