source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'

pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

pod 'pop', '~> 1.0'

pod 'ACEExpandableTextCell'

pod 'IQKeyboardManager'

pod 'AFNetworking'

pod 'CustomIOSAlertView'

pod 'MJRefresh'

pod 'Reachability'

pod 'SDWebImage'

pod 'PopMenu'

pod 'Qiniu'

